'use strict';

define( function () {
    var events  = angular.module( 'events', []);

    events.constant( 'events', {
        ACTIVITIES_CREATED      : 'activities.created',
        ACTIVITIES_DELETED      : 'activities.deleted',
        ACTIVITIES_ERROR        : 'activities.error',
        ACTIVITIES_QUERIED      : 'activities.queried',
        ACTIVITIES_RETRIEVED    : 'activities.retrieved',
        ASSIGNMENTS_CREATED     : 'assignments.created',
        ASSIGNMENTS_DELETED     : 'assignments.deleted',
        ASSIGNMENTS_ERROR       : 'assignments.error',
        ASSIGNMENTS_QUERIED     : 'assignments.queried',
        ASSIGNMENTS_RETRIEVED   : 'assignments.retrieved',
        COMMENTS_CREATED        : 'comments.created',
        COMMENTS_DELETED        : 'comments.deleted',
        COMMENTS_ERROR          : 'comments.error',
        COMMENTS_QUERIED        : 'comments.queried',
        COMMENTS_RETRIEVED      : 'comments.retrieved',
        COURSES_CREATED         : 'courses.created',
        COURSES_DELETED         : 'courses.deleted',
        COURSES_ERROR           : 'courses.error',
        COURSES_QUERIED         : 'courses.queried',
        COURSES_RETRIEVED       : 'courses.retrieved',
        DISCUSSIONS_CREATED     : 'discussions.created',
        DISCUSSIONS_DELETED     : 'discussions.deleted',
        DISCUSSIONS_ERROR       : 'discussions.error',
        DISCUSSIONS_QUERIED     : 'discussions.queried',
        DISCUSSIONS_RETRIEVED   : 'discussions.retrieved',
        FILES_CREATED           : 'files.created',
        FILES_DELETED           : 'files.deleted',
        FILES_ERROR             : 'files.error',
        FILES_QUERIED           : 'files.queried',
        FILES_RETRIEVED         : 'files.retrieved',
        GRADES_CREATED          : 'grades.created',
        GRADES_DELETED          : 'grades.deleted',
        GRADES_ERROR            : 'grades.error',
        GRADES_QUERIED          : 'grades.queried',
        GRADES_RETRIEVED        : 'grades.retrieved',
        LOGIN_ERROR             : 'login.error',
        LOGIN_SUCCESS           : 'login.success',
        LOGOUT_ERROR            : 'logout.error',
        LOGOUT_SUCCESS          : 'logout.success',
        SYSTEM_MESSAGE          : 'system.message',
        QUESTIONARIES_CREATED   : 'questionaries.created',
        QUESTIONARIES_DELETED   : 'questionaries.deleted',
        QUESTIONARIES_ERROR     : 'questionaries.error',
        QUESTIONARIES_QUERIED   : 'questionaries.queried',
        QUESTIONARIES_RETRIEVED : 'questionaries.retrieved',
        USERS_CREATED           : 'users.created',
        USERS_DELETED           : 'users.deleted',
        USERS_ERROR             : 'users.error',
        USERS_QUERIED           : 'users.queried',
        USERS_RETRIEVED         : 'users.retrieved'
    });
});